core/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('notebook.urls', namespace='notebook')),
    url(r'^admin/', admin.site.urls),
]

notebook/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^auto-complete$', views.auto_complete, name='auto_complete'),
    url(r'^instant-search$', views.instant_search, name='instant_search')
]

app_name = 'notebook'

notebook/models.py
from django.db import models


class Account(models.Model):
    username = models.CharField(max_length=40)
    service = models.CharField(max_length=40)

    def __str__(self):
        return self.username + "@" + self.service


class Contact(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=60)
    company = models.CharField(max_length=40)
    address = models.CharField(max_length=60)
    city = models.CharField(max_length=20)
    county = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    zip_code = models.CharField(max_length=8)
    phone = models.CharField(max_length=20)
    fax = models.CharField(max_length=20)
    web = models.CharField(max_length=30)
    followers = models.IntegerField(default=0)
    note = models.TextField()
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    accounts = models.ManyToManyField(Account)

    def __str__(self):
        return self.name

    def account_names(self):
        return [str(account) for account in self.accounts.all()]

    def account_ids(self):
        return [account.id for account in self.accounts.all()]

notebook/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from algoliasearch_django import get_adapter
from .models import Contact

def index(request):
    return redirect('notebook:instant_search', permanent=True)

def auto_complete(request):
    context = {
        'appID': settings.ALGOLIA['APPLICATION_ID'],
        'searchKey': settings.ALGOLIA['SEARCH_API_KEY'],
        'indexName': get_adapter(Contact).index_name
    }
    return render(request, 'notebook/auto_complete.html', context)

def instant_search(request):
    context = {
        'appID': settings.ALGOLIA['APPLICATION_ID'],
        'searchKey': settings.ALGOLIA['SEARCH_API_KEY'],
        'indexName': get_adapter(Contact).index_name
    }
    return render(request, 'notebook/instant_search.html', context)

notebook/templates/notebook/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AlgoliaSearch Example | {% block title %}{% endblock %}</title>

    <link href="//cdn.jsdelivr.net/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">

    {% block css %}
    {% endblock %}

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="http://www.algolia.com">Algolia</a>
          </div>

          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url "notebook:instant_search" %}">Instant-search</a></li>
              <li><a href="{% url "notebook:auto_complete" %}">Auto-complete</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      {% block content %}
      <h1>Hello, world!</h1>
      {% endblock %}
    </div>

    <script src="//cdn.jsdelivr.net/jquery/2.1.4/jquery.js"></script>
    <script src="//cdn.jsdelivr.net/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.jsdelivr.net/g/algoliasearch,algoliasearch.helper"></script>

    {% block javascript %}
    {% endblock %}
  </body>
</html>

notebook/templates/notebook/auto_complete.html
{% extends "notebook/_base.html" %}

{% block title %}Auto-complete{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    <p class="lead">A modern auto-complete field based on <code>typeahead.js</code> + <code>Hogan</code> and <code>AlgoliaSearch JS Client</code> example.</p>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <p class="text-center search-terms">
    Try
    <a href="javascript:void(0)">John</a>,
    <a href="javascript:void(0)">Jonn</a>,
    <a href="javascript:void(0)">s row</a>,
    <a href="javascript:void(0)">roeb</a>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <input id="q" placeholder="Search" autocomplete="off" autocorrect="false" spellcheck="false" type="search" />
  </div>
</div>

{% endblock %}

{% block javascript %}
<script src="//cdn.jsdelivr.net/typeahead.js/0.10/typeahead.jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/hogan.js/3.0/hogan.min.js"></script>

{% verbatim %}
<script type="text/template" id="autocomplete">
<p>
  {{{ _highlightResult.name.value }}}({{{ _highlightResult.email.value }}})
</p>
</script>
{% endverbatim %}

<script>
$(document).ready(function() {
  var $inputField = $('#q');

  var template = Hogan.compile($('#autocomplete').text());

  var client = algoliasearch('{{ appID }}', '{{ searchKey }}');
  var index = client.initIndex('{{ indexName }}');

  $('.search-terms a').click(function(e) {
    $inputField.val($(this).text()).change().focus();
  });

  $inputField.typeahead({hint: false}, {
    source: index.ttAdapter(),
    displayKey: 'email',
    templates: {
      suggestion: function(hit) {
        return template.render(hit);
      }
    }
  }).on('change', function(e) {
    console.log('on(change): ' + $inputField.val());
  }).on('keypress', function(e) {
    console.log('on(submit): ' + $inputField.val());
  }).on('typeahead:selected', function(e) {
    console.log('on(selected): ' + $inputField.val());
  });
});
</script>
{% endblock %}

notebook/templates/notebook/instant_search.html
{% extends "notebook/_base.html" %}
{% load static %}

{% block title %}Instant-search{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    <p class="lead">A <code>Google-like</code> instant-search based on <code>AlgoliaSearch JS Client</code> + <code>Hogan</code> example.</p>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <input id="q" name="q" placeholder="Search" autocomplete="off" autocorrect="false" spellcheck="false" class="form-control" type="search" />
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <p class="text-center search-terms">
    Try
    <a href="javascript:void(0)">John</a>,
    <a href="javascript:void(0)">Jonn</a>,
    <a href="javascript:void(0)">s row</a>,
    <a href="javascript:void(0)">roeb</a>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-sm-12" id="hits-stat">
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div id="no-hits" class="col-sm-12 hidden"></div>

    <table id="hits-table" class="table table-striped hidden">
      <thead>
        <tr>
          <th style="width: 30%;">Name</th>
          <th style="witdh: 35%;">Company</th>
          <th style="width: 35%;">Email</th>
        </tr>
      </thead>
      <tbody id="hits">
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

{% block javascript %}
<script src="//cdn.jsdelivr.net/hogan.js/3.0.2/hogan.min.js"></script>

{% verbatim %}
<script type="text/template" id="hit-template">
<tr>
  <td>{{{ _highlightResult.name.value }}}</td>
  <td>{{{ _highlightResult.company.value }}}</td>
  <td><a href="mailto:{{ email }}">{{{ _highlightResult.email.value }}}</a></td>
</tr>
</script>
{% endverbatim %}

<script>
$(document).ready(function() {
  var $inputField = $('#q');
  var $hits = $('#hits');
  var $hitsTable = $('#hits-table');
  var $noHits = $('#no-hits');
  var $hitsStat = $('#hits-stat');

  var hitTemplate = Hogan.compile($('#hit-template').text());

  var client = algoliasearch('{{ appID }}', '{{ searchKey }}');
  var helper = algoliasearchHelper(client, '{{ indexName }}');

  $('.search-terms a').click(function(e) {
    $inputField.val($(this).text()).change().focus();
    $inputField.keyup();
  });

  $inputField.on('keyup', function() {
    var query = $inputField.val();
    helper.setQuery(query).search();
  }).focus();

  helper.on('result', function(data) {
    renderHits(data);
  });

  helper.search(); // first search

  function renderHits(content) {
    var hitsHtml = '';

    if (content.hits.length === 0) {
      hitsHtml = '<p class="text-center text-danger lead">We didn\'t find any results for your search.</p>';
      $noHits.html(hitsHtml);
      $noHits.removeClass('hidden');
      $hitsTable.addClass('hidden');
    } else {
      for (var i = 0; i < content.hits.length; ++i) {
        hitsHtml += hitTemplate.render(content.hits[i]);
      }

      $hits.html(hitsHtml);
      $hitsTable.removeClass('hidden');
      $noHits.addClass('hidden');
    }

    $hitsStat.html('<p class="text-right">Found <b>' +
        content.nbHits + '</b> results in <b>' + content.processingTimeMS + '</b>ms, ' +
        'by <a href="http://www.algolia.com"><img src="{% static "img/logo-algolia.png" %}" /></a></p>'
    );
  }
});
</script>
{% endblock %}